const menuList = [
    {
        title: '首页',
        key: '/admin/homePage',
        type:'dashboard'
    },
    {
        title:'采购管理',
        key:'/admin/purchasing',
        type:'shopping-cart',
        childrenItem:[
            {
                title:'新增单据',
                key:'/purchasingAdd',
                children:[
                    {
                        title:'采购入库单',
                        key:'/admin/purchasing/receive',
                        type:'plus'
                    }
                ]
            },
            {
                title:'单据列表',
                key:'/admin/purchasingList',
                children:[
                    {
                        title:'采购订单列表',
                        key:'/admin/purchasing/orderList',
                    },
                    {
                        title:'采购入库单列表',
                        key:'/admin/purchasing/receiveList',
                    },
                    {
                        title:'采购退货单列表',
                        key:'/admin/purchasing/returnList',
                    }
                ]
            }
        ]
    },
    {
        title:'库存管理',
        key:'/admin/inventory',
        type:'home',
        childrenItem:[
            {
                title:'新增单据',
                key:'/inventoryAdd',
                children:[
                    {
                        title:'盘点',
                        key:'/admin/inventory/order',
                        type:'plus'
                    },
                    {
                        title:'其他入库单',
                        key:'/admin/inventory/entry',
                        type:'plus'
                    },
                    {
                        title:'其他出库单',
                        key:'/admin/inventory/delivery',
                        type:'plus'
                    }
                ]
            },
            {
                title:'单据列表',
                key:'/admin/purchasingList',
                children:[
                    {
                        title:'盘点列表',
                        key:'/admin/inventory/orderList',
                    },
                    {
                        title:'其他入库单列表',
                        key:'/admin/inventory/entryList',
                    },
                    {
                        title:'其他出库单列表',
                        key:'/admin/inventory/deliveryList',
                    }
                ]
            }
        ]
    },
    {
        title:'销售管理',
        key:'/admin/sale',
        type:'pie-chart',
        childrenItem:[
            {
                title:'新增单据',
                key:'/saleAdd',
                children:[
                    {
                        title:'销售出库单',
                        key:'/admin/sale/delivery',
                        type:'plus'
                    }
                ]
            },
            {
                title:'单据列表',
                key:'/admin/saleList',
                children:[
                    {
                        title:'销售订单列表',
                        key:'/admin/sale/orderList',
                    },
                    {
                        title:'销售出库列表',
                        key:'/admin/sale/deliveryList',
                    },
                    {
                        title:'销售退货列表',
                        key:'/admin/sale/refundList',
                    }
                ]
            }
        ]
    },
    {
        title:'报表',
        key:'/admin/reportForm',
        type:'bar-chart',
        children:[
            {
                title:'采购报表',
                key:'/admin/reportForm/purchase',
                children:[
                    {
                        title:'采购订单明细',
                        key:'/admin/reportForm/purchase/detail'
                    },
                    {
                        title:'采购退货明细',
                        key:'/admin/reportForm/purchase/refundDetail'
                    },
                    {
                        title:'采购入库明细',
                        key:'/admin/reportForm/purchase/storageDetail'
                    },
                    {
                        title:'采购统计',
                        key:'/admin/reportForm/purchase/statistic'
                    }
                ]
            },
            {
                title:'仓库报表',
                key:'/admin/reportForm/Inventory',
                children:[
                    {
                        title:'库存余额',
                        key:'/admin/reportForm/Inventory/stock'
                    },
                    {
                        title:'盘点明细',
                        key:'/admin/reportForm/Inventory/detail'
                    },
                    {
                        title:'其他入库明细',
                        key:'/admin/reportForm/Inventory/entryDetail'
                    },
                    {
                        title:'其他出库明细',
                        key:'/admin/reportForm/Inventory/deliveryDetail'
                    }
                ]
            },
            {
                title:'销售报表',
                key:'/admin/reportForm/sale',
                children:[
                    {
                        title:'销售订单明细',
                        key:'/admin/reportForm/sale/detail'
                    },
                    {
                        title:'销售出库明细',
                        key:'/admin/reportForm/sale/deliveryDetail'
                    },
                    {
                        title:'销售退货明细',
                        key:'/admin/reportForm/sale/refundDetail'
                    }
                ]
            }
        ]
    },
    {
        title:'基础资料',
        key:'/admin/basicData',
        type:'file-text',
        childrenItem:[
            {
                title:'基础资料',
                key:'/admin/basicDataTitle',
                children:[
                    {
                        title:'产品',
                        key:'/admin/basicData/product'
                    },
                    {
                        title:'客户',
                        key:'/admin/basicData/customer'
                    },
                    {
                        title:'供应商',
                        key:'/admin/basicData/supplier'
                    },
                    {
                        title:'仓库',
                        key:'/admin/basicData/warehouse'
                    }
                ]
            }
        ]
    }
];
export default menuList;